# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiSiYeMeiEr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'MJRefresh', '~> 3.5.0'
  pod 'Masonry', '~> 1.1.0'
  #HTML
  pod 'DTCoreText'
#  pod 'YDADSDK','~>2.16.12'
#  pod 'SDWebImage', '~>5.12.6'
  target 'DiSiYeMeiErTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiSiYeMeiErUITests' do
    # Pods for testing
  end

end
